/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'arikawa' at '16/06/27 20:45' with Gradle 2.5
 *
 * @author arikawa, @date 16/06/27 20:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
